### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by ousamabenyounes** [odecharette/Becowo#1]
Your parameters.yml file has been compromised and your login/pwd are now visible on this link:
this project
to remove it from your history:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Change your login/pwd on all your projects / demo / mails / Algolia Accounts quickly!

I recommand you also to use a gitignore file on the root of your Symfony project:
https://github.com/github/gitignore/blob/master/Symfony.gitignore
This will automatically ignore your parameters.yml file, your vendors ...

Hope this will help you :)

**Comment by odecharette** [comment]
.... thanks !

**Comment by ousamabenyounes** [comment]
sorry but it is still available...
https://github.com/odecharette/Becowo/commit/23b9cc356adf38a3214058773122ddb9400ba683

You have two options:
- follow this tutorial: https://help.github.com/articles/removing-sensitive-data-from-a-repository/
- remove the project and create a new one with no git history so it won't be possible for us to view your passwords...

Good luck
